@startuml DFD_A_secure
actor Patient #777777
actor "Receptionist" as Rec #10295A

rectangle "<&oi_lock_locked> P1  API Gateway\n(TLS 1.3)" as P1 #87B3FF

database  "<&oi_lock_locked> D2  Patients DB\n(tag: pii, AES-256)" as D2
cloud     "<&oi_lock_locked> S3  Scans Storage\n(tag: pii/high, AES-256, retention:365d)" as S3

Patient --> P1 : JSON (PD-01/02)
Rec     --> P1 : Ввод данных
P1      --> D2 :  INSERT (через Patient Service) (RLS mask)
P1      --> S3 : PUT JPG (OCR-mask)
@enduml
