@startuml DFD_C_Lab
actor Doctor     #10295A
actor Laboratory #777777

rectangle "P3  Заказ анализа"        as P3 #87B3FF
rectangle "P4  Получение результата" as P4 #87B3FF

file D3 as "Файлы сканов (PDF)"

Doctor --> P3 : Направление + PD-01/02
P3 --> Laboratory : API / e-mail (PDF)
Laboratory --> P4 : Результат анализа (LAB-01)
P4 --> D3 : PDF сохраняется
@enduml
