@startuml DFD_C_secure
actor Doctor #10295A
actor Laboratory #777777

rectangle "<&oi_lock_locked> Lab-Order-API\n(TLS 1.3)" as P3
rectangle "<&oi_lock_locked> Lab-Callback-API\n(TLS 1.3)" as P4

database "<&oi_lock_locked> Orders DB\n(tag: phi, AES-256)" as ORD
cloud    "<&oi_lock_locked> Lab-PDF Bucket\n(tag: phi, AES-256)" as S3

Doctor --> P3 : order (tokenised ID only)
P3 --> ORD : сохранение заказа
P3 --> Laboratory : HTTPS + JWT (только ID)
Laboratory --> P4 : PDF результат (phi)
P4 --> S3 : PUT PDF
@enduml
