@startuml DFD_D_secure
actor Patient #777777
actor Cassier #10295A

rectangle "<&oi_lock_locked> P5 POS-Gateway\n(TLS 1.2)" as P5

rectangle "<&oi_lock_locked> 1C Касса\n(AES-256)" as POS
rectangle "<&oi_lock_locked> 1C Бухгалтерия\n(AES-256)" as ACC

database "<&oi_lock_locked> PAY DB\n(tag: financial, AES-256)" as PAY

Patient --> Cassier : карта / нал
Cassier --> P5
P5 --> POS : PAN (mask #### #### #### 1234)
POS --> PAY
POS --> ACC : проводка
@enduml