@startuml DFD_E_secure
actor "Warehouse keeper" as WH #10295A

rectangle "<&oi_lock_locked> P6 Inventory-Service\n(TLS 1.3)" as P6

rectangle "<&oi_lock_locked> 1C Склад\n(AES-256)" as INV
rectangle "<&oi_lock_locked> 1C Бухгалтерия\n(AES-256)" as ACC

WH --> P6 : накладная (tag: financial)
P6 --> INV : движение (ABAC → role=warehouse)
INV --> ACC : проводка
@enduml
